### ISSUE TITLE
Protocol buffer import capability

### ISSUE THREAD

**Issue by anzdaddy** [arr-ai/arrai#478] opened 2020-06-19 02:11 UTC
Currently, we JSON-ify protobuf payloads for use in arr.ai code. JSON is somewhat lossy because it can't differentiate between struct-like and map-like data objects (think `customer` vs `map[custid]customer`), and the safe option is to map all JSON objects to dictionaries. If we support direct proto imports, we solve a few significant limitations in one go:

1. Map messages to tuples, so we can write `customer.dob` instead of `customer('dob')`.
1. Make proto ingestion safe under changes to field names.
1. Support proto map types (mapping them to dicts), including maps with non-string keys.

Rather than figuring out how to execute the `protoc` compiler, which seems to be the only supported mechanism to parse .proto files, we should assume a pb message conforming to [descriptor.proto](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto) as the starting point for parsing a protocol buffer message.

**Comment by orlade-anz** [comment] 2020-06-19 03:49
I see three parts to this:
1. Defining and documenting a standard data structure for a Sysl model in arr.ai (i.e. messages as tuples, maps as maps)
2. A function to convert the text of a Sysl textpb into that standard structure.
3. Some (standard?) library package to invoke that function.

I don't know if 3. should be part of the standard library, because it's not core to arr.ai... but at the same time it will probably be the primary use case for arr.ai in the foreseeable future, so using an external package reference seems crufty.

So I vote for standard library, something like `//sysl.parse(//os.file(foo.sysl))`. @anzdaddy should weight in though.

**Comment by marcelocantos** [comment] 2020-06-19 11:38
While reading Sysl protos is a prime motivation, I'm thinking of a more general capability:

```bash
$ protoc -o sysl.pb sysl.proto
$ sysl pb --mode=pb -o petshop.pb demo/petshop/petshop.sysl
$ ai
@> /set sysl = //encoding.proto.descriptor(//os.file("sysl.pb"))
@> /set petshop = sysl.decode(//os.file("petshop.pb"))
(
    apps: {
        'PetShopApi': (
            name: (part: ['PetShopApi']),
            attrs: {
                'package': (s: "io.sysl.demo.petshop.api"),
                'patterns': (a: (elt: [(s: "rest")])),
            },
            endpoints: {
                'GET /petshop': (
                    name: 'GET /petshop',
                    attrs: {'patterns': (a: (elt: [(s: 'rest')]))},
                    stmt: (ret: (payload: "PetShop")),
                    rest_params: (
                        method: 'GET',
                        path: '/petshop',
                    )
                    source_context: (
                        file: 'petshop.sysl',
                        start: (
                            line: 39,
                            col: 8,
                        ),
                        end: (
                            line: 42,
                            col: 4,
                        ),
                    )
                )
            }
            ...
        ),
    },
)
```

(Note: `--mode=pb`, denoting binary protobuf format, isn't currently implemented, but should be. This is important for ensuring backwards compability when field names change in the .proto.)

**Comment by ericzhang6222** [comment] 2020-06-22 06:48
In my mind, I want to implement it like this:
```
$ protoc -o sysl.pb sysl.proto
$ sysl pb --mode=pb -o petshop.pb demo/petshop/petshop.sysl
$ ai
@> /set sysl = //encoding.proto.descriptor(//os.file("sysl.pb"))
@> /set petshop = sysl.decode(//os.file("petshop.pb"))
@>
@> /set petshopTuple = petshop.tuple()
@>
@> petshopTuple.apps
@> [PetShopApi, PetShopApiToModel, PetShopFacade, PetShopModel, PetShopModelToApi]
@>
@> petshopTuple.PetShopApi.endpoints
@> ["GET /petshop"]
```

**Comment by marcelocantos** [comment] 2020-06-22 10:47
`petshop.tuple()` is illegal. There are no zero-argument functions in arr.ai. What's the intent?

**Comment by ericzhang6222** [comment] 2020-06-23 02:06
> `petshop.tuple()` is illegal. There are no zero-argument functions in arr.ai. What's the intent?

It is used to transform json/map to tuple.

> There are no zero-argument functions in arr.ai.

What's the design thought?

**Comment by marcelocantos** [comment] 2020-06-23 04:42
JSON is not involved at all here. `sysl.pb` is a binary protocol buffer conforming to [descriptor.proto](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto). `petshop.pb` is a binary protocol buffer conforming to [sysl.proto](https://github.com/anz-bank/sysl/blob/master/pkg/sysl/sysl.proto). The output of `sysl.decode` should be the final tuple.

**Comment by ericzhang6222** [comment] 2020-06-28 16:26
I investigated in this week and I think the proper approach is following one:

1. Read `.proto` definition file to descriptor,
2. Build protocol buffer message by [`dynamicpb.NewMessage(desc)`](https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/types/dynamicpb?tab=doc#NewMessage),
3. Unmarshal binay message by [`proto.Unmarshal(data, msg)`](https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/proto?tab=doc#Unmarshal),
4. Then get data from message by `descriptor`, and build `tuple` in arrai.

And I didn't find an existing API which can read `.proto` definition file successfully, parse and generate `descriptor` in new [protobuf APIs](https://pkg.go.dev/google.golang.org/protobuf@v1.25.0). The [old protobuf API](https://github.com/golang/protobuf/blob/master/proto/registry.go#L57) can do this, but it is deprecated. And as the [old API doc](https://github.com/golang/protobuf/blob/master/proto/registry.go#L56), Use [`protoregistry.GlobalFiles.FindFileByPath`](https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/reflect/protoregistry?tab=doc#Files.FindFileByPath) instead. I tried and it can't work, I am still check the root cause.

There is an [example](https://github.com/Windfarer/dynamic-protobuf-example/blob/master/main.go) which display the similar thoughts to this approach.

As team discussed, it can handle Sysl first. So in order to make sure this feature can be released ASAP, I preferred this fast approach, import sysl code for protocol buffer messages, and hardcode to generate tuple in arrai. The code looks like
```
import (
	"fmt"
	"io/ioutil"
	"testing"

	"github.com/anz-bank/sysl/pkg/sysl"
	"github.com/stretchr/testify/assert"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/dynamicpb"
)

func TestFastWay(t *testing.T) {
	in, err := ioutil.ReadFile("../../examples/protocolbuffer/sysl/petshop")
	assert.Nil(t, err)
	module := &sysl.Module{}
	err = proto.Unmarshal(in, module)
	assert.Nil(t, err)

	apps := module.GetApps()

	assert.NotNil(t, apps["PetShopApi"])
        // Build tuple by call methods in sysl.Module
}
```

**Comment by anz-gordonj7** [comment] 2020-06-29 05:15
I'm not sure I agree with this approach. Yes, being able to import protobufs directly is a good idea but misses the point of what is actually needed right now.

Basically I see the problem as there being a mismatch between the sysl protobuf data model and the arrai relational model. It seems to me that if the pb was imported into automatically linked relational tables then everything becomes far more trivial. Much simpler relational ops could be used instead of doing multiple levels of lookups for something trivial like "What endpoints does this endpoint call?"

Of course this isnt likely doable automatically and needs to be manually built up, but that's fine.

**Comment by marcelocantos** [comment] 2020-06-29 06:43
With a clean protobuf representation in arr.ai, we can write a transform from the hierarchical protobuf schema to a relational schema. We can also write a round trip transform back to the hierarchical model and check that no information is lost in the process.

With this bijection in place, when we eventually reimplement the arr.ai parser as wbnf-in-arr.ai, then we can transform the ast directly to the relational schema with a high degree of confidence that we're not breaking anything in the process.

This approach isn't the most direct, but it is much smoother and provides checks and balances along the way that we won't have if we go straight to a relational schema without the bijection.

Strictly speaking, we could transition from the current JSON representation and achieve similar results. However, since the JSON form isn't very pleasant to work with, and we plan to implement protobuf support anyway, going down that path will make the transition a bit easier for zero nett cost.

**Comment by marcelocantos** [comment] 2020-06-29 06:57
One further thought on the proto library: there is an opportunity to regularise things a bit here. Currently, the following:
```arrai
@> /set sysl = //encoding.proto.descriptor(//os.file("sysl.pb"))
@> /set petshop = sysl.decode(//os.file("petshop.pb"))
```
produces two completely different kinds of object:
1. `sysl` is a library of capabilities related to parsing protobufs that conform to `sysl.pb`.
1. `petshop` is a tuple that represents the decoded form of `petshop.pb`.

There's a missing intermediate step, which is a tuple representing the decoded form of `sysl.pb`. Since both `.pb` files are just protocol buffers conforming to their respective `.proto` schemas, it feels as though there should be some symmetry, like so:
```arrai
@> /set proto = //encoding.proto.decode(//encoding.proto.pb, //os.file("proto.pb"))
@> /set sysl = //encoding.proto.decode(proto, //os.file("sysl.pb"))
@> /set petshop = //encoding.proto.decode(sysl, //os.file("petshop.pb"))
```

Note that the first line in the above trio is technically valid, it wouldn't be needed in practice because `proto` is in fact equal to `//encoding.proto.pb`.

**Comment by marcelocantos** [comment] 2020-06-29 23:57
An additional function might be needed: `//encoding.proto.parse(//os.file("sysl.proto"))`. It should be equivalent to `//encoding.proto.decode(//encoding.proto.pb, //os.file("sysl.pb"))`, assuming `sysl.pb` is the output of `protoc -o sysl.pb sysl.proto`.

**Comment by ericzhang6222** [comment] 2020-07-06 10:44
Current implemented syntax is
```
@> /set sysl = //encoding.proto.decode(//encoding.proto.proto, //os.file('./translate/pb/test/sysl.pb'))
@> /set decodeSyslPb = //encoding.proto.decode(sysl)
@> /set petshop = decodeSyslPb("Module" , //os.file("./translate/pb/test/petshop.pb"))
@> petshop.apps("PetShopApi").attrs('package').s
'io.sysl.demo.petshop.api'
```

**Comment by ericzhang6222** [comment] 2020-07-06 10:47
> An additional function might be needed: `//encoding.proto.parse(//os.file("sysl.proto"))`. It should be equivalent to `//encoding.proto.decode(//encoding.proto.pb, //os.file("sysl.pb"))`, assuming `sysl.pb` is the output of `protoc -o sysl.pb sysl.proto`.

Maybe we can do it later as I haven't found a API parses `sysl.proto` which is plain text format to `FileDescriptor`.

**Comment by marcelocantos** [comment] 2020-07-06 11:50
> > An additional function might be needed: `//encoding.proto.parse(//os.file("sysl.proto"))`. It should be equivalent to `//encoding.proto.decode(//encoding.proto.pb, //os.file("sysl.pb"))`, assuming `sysl.pb` is the output of `protoc -o sysl.pb sysl.proto`.
> 
> Maybe we can do it later as I haven't found a API parses `sysl.proto` which is plain text format to `FileDescriptor`.

That's fine. I thought you had found one in `protoregistry`, but if not, this isn't part of MVP, so let's skip it. I suspect we will always have to precook .proto files using `protoc` as a separate part of a build pipeline.

**Comment by ericzhang6222** [comment] 2020-07-07 02:28
@marcelocantos can you provide more details on "I suspect we will always have to precook .proto files using protoc as a separate part of a build pipeline."?

**Comment by ericzhang6222** [comment] 2020-07-07 02:52
@marcelocantos @orlade-anz do we need to add an operator `filter out` on the arr.ai tuple for protobuf which can help to remove unnecessary attributes like `SourceContext`? Current operator `filter` can't help now.

**Comment by ericzhang6222** [comment] 2020-07-09 07:46
Reopened as following pending items:
https://github.com/arr-ai/arrai/issues/478#issuecomment-654186357
https://github.com/arr-ai/arrai/issues/478#issuecomment-654567482

**Comment by ericzhang6222** [comment] 2020-07-09 07:55
Closed and track pending issue via #496

**Closed by ericzhang6222** 2020-07-09 07:55 UTC
Labels: P0, enhancement

**Comment by ericzhang6222** [comment] 2020-07-13 09:00
@marcelocantos,  
@orlade-anz and I discussed current implementation today
```
@> /set sysl = //encoding.proto.decode(//encoding.proto.proto, //os.file('./translate/pb/test/sysl.pb'))
@> /set decodeSyslPb = //encoding.proto.decode(sysl)
@> /set petshop = decodeSyslPb("Module" , //os.file("./translate/pb/test/petshop.pb"))
@> petshop.apps("PetShopApi").attrs('package').s
'io.sysl.demo.petshop.api'
```
The 1st line `//encoding.proto.decode` has 2 arguments, and both argument data types are `bytes`. 2nd line `//encoding.proto.decode` has 1 argument only and whose data type is `bytes`. 
And as 2nd and 3rd lines, the calling of method `//encoding.proto.decode`, 1st argument type is `bytes`, 2nd argument type is `string`. It is different from calling in 1st line. 

Looks like it is not symmetrical. Can you help to confirm if it is necessary to change?

Now the possible changes are:
```
let sysl = //encoding.proto.decode(//os.file('sysl.pb'));
let shop = //encoding.proto.decode(sysl, 'Module', //os.file("petshop.pb"));
```

```
let sysl = //encoding.proto.decode(//encoding.proto.proto, //os.file('sysl.pb'));
let decodeSyslPb = //encoding.proto.decode(//encoding.proto.proto, sysl);
let petshop = decodeSyslPb("Module" , //os.file("petshop.pb"));
petshop.apps("PetShopApi").attrs('package').s
```

**Comment by marcelocantos** [comment] 2020-08-08 02:38
> @marcelocantos @orlade-anz do we need to add an operator `filter out` on the arr.ai tuple for protobuf which can help to remove unnecessary attributes like `SourceContext`? Current operator `filter` can't help now.

Tuple projections are orthogonal to transform operators. #550 proposes a new syntax that supports exclusions.
