### ISSUE TITLE
--version flag for CLI

### ISSUE THREAD

**Issue by orlade** [arr-ai/arrai#300] opened 2020-05-22 07:26 UTC
Please **do not post any internal, closed source snippets** on this public issue tracker!

### Current arrai Version

0.2 (I think!)

### Use-cases

I want to know what version I'm running to submit more feature requests :)

### Attempted Solutions

arrai --version
arrai -version
arrai version
arrai --help

**Comment by marcelocantos** [comment] 2020-05-23 08:14
Duplicate of #246

**Closed by marcelocantos** 2020-05-23 08:14 UTC
Labels: enhancement
