### ISSUE TITLE
Fix multiple cases cond statement error

### ISSUE THREAD

**Issue by ChloePlanet** [arr-ai/arrai#472] opened 2020-06-17 07:06 UTC
### Description
```
$ go run ./cmd/arrai e "{1, [2, 3], 4, [5, 6]} where cond . {k: true, [a, b]: true} => cond . {[a, b]: a + b, k:k}"
{1, 4, 5, 11} # OK
```
```
$ go run ./cmd/arrai e "{1, [2, 3], 4, [5, 6]} where cond . {k: true, [a, b]: true} => cond . {k: k, [a, b]: a + b}"
{1, 4, [2, 3], [5, 6]} # WRONG, supposed to be {1, 4, 5, 11} (the same as previous one)
```

### Your Environments
```sh
$ go version
go version go1.13 darwin/amd64
```

**Comment by ericzhang6222** [comment] 2020-06-17 08:12
Looks like this is an enhancement, will discuss more with @ChloePlanet

**Comment by ericzhang6222** [comment] 2020-06-19 08:15
@ChloePlanet, the root cause is ident binding, the code is in pattern_expr.go
```
if identExpr, is := p.Expr.(IdentExpr); is {
  // Bind value for identexpr in Pattern, like `let (a: x, b: y) = (a: 4, b: 7); x`
 return Scope{}.With(identExpr.ident, value), nil
}
```
In case `{1, [2, 3], 4, [5, 6]} where cond . {k: true, [a, b]: true} => cond . {k: k, [a, b]: a + b}`, `[2, 3]` can be bound to `k` too as current implementation. It mixes up `cond` evaluation and cause s can't calculate `a + b` correctly.
I tried and didn't find a simple and quick fixing. As it can be fixed by workaround like changing order to `{[a, b]: a + b , k: k}`, so can we adjust its priority to P1? Then I can work on #478 which is high priority.

arrai version:
`arrai v0.79.0 darwin/amd64`

**Comment by ericzhang6222** [comment] 2020-06-19 09:24
@ChloePlanet, still can you confirm if it is a valid issue too?

**Comment by marcelocantos** [comment] 2020-06-19 10:06
`cond` is order dependent. The second case:
```arrai
{1, [2, 3], 4, [5, 6]} where cond . {k: true, [a, b]: true} => cond . {k: k, [a, b]: a + b}
```
is working as intended, since `k` should match anything. Longer term, the compiler should error on this because the `[a, b]` condition is unreachable.

**Comment by ericzhang6222** [comment] 2020-06-19 10:42
> `cond` is order dependent. It tries patterns from left to right and stops at the first match. So the second case:
> 
> ```
> {1, [2, 3], 4, [5, 6]} where cond . {k: true, [a, b]: true} => cond . {k: k, [a, b]: a + b}
> ```
> 
> is working as intended, since `k` should match anything. In fact, the compiler should error on this because the `[a, b]` condition is unreachable.

Will add error for this case.

**Comment by marcelocantos** [comment] 2020-06-22 06:31
Working as intended. Closing.

**Closed by marcelocantos** 2020-06-22 06:31 UTC
Labels: P0, bug
